export const iso2ToDial = {
  af: 93,
  ax: 358,
  al: 355,
  dz: 213,
  as: 1684,
  ad: 376,
  ao: 244,
  ai: 1264,
  aq: 672,
  ag: 1268,
  ar: 54,
  am: 374,
  aw: 297,
  au: 61,
  at: 43,
  az: 994,
  bs: 1242,
  bh: 973,
  bd: 880,
  bb: 1246,
  by: 375,
  be: 32,
  bz: 501,
  bj: 229,
  bm: 1441,
  bt: 975,
  bo: 591,
  ba: 387,
  bw: 267,
  bv: 47,
  br: 55,
  io: 246,
  vg: 1284,
  bn: 673,
  bg: 359,
  bf: 226,
  bi: 257,
  kh: 855,
  cm: 237,
  ca: 1,
  cv: 238,
  bq: 599,
  ky: 1345,
  cf: 236,
  td: 235,
  cl: 56,
  cn: 86,
  cx: 61,
  cc: 61,
  co: 57,
  km: 269,
  cd: 243,
  cg: 242,
  ck: 682,
  cr: 506,
  ci: 225,
  hr: 385,
  cu: 53,
  cw: 599,
  cy: 357,
  cz: 420,
  dk: 45,
  dj: 253,
  dm: 1767,
  do: 1,
  ec: 593,
  eg: 20,
  sv: 503,
  gq: 240,
  er: 291,
  ee: 372,
  et: 251,
  fk: 500,
  fo: 298,
  fj: 679,
  fi: 358,
  fr: 33,
  gf: 594,
  pf: 689,
  tf: 262,
  ga: 241,
  gm: 220,
  ge: 995,
  de: 49,
  gh: 233,
  gi: 350,
  gr: 30,
  gl: 299,
  gd: 1473,
  gp: 590,
  gu: 1671,
  gt: 502,
  gg: 44,
  gn: 224,
  gw: 245,
  gy: 592,
  ht: 509,
  hm: 672,
  hn: 504,
  hk: 852,
  hu: 36,
  is: 354,
  in: 91,
  id: 62,
  ir: 98,
  iq: 964,
  ie: 353,
  im: 44,
  il: 972,
  it: 39,
  jm: 1876,
  jp: 81,
  je: 44,
  jo: 962,
  kz: 7,
  ke: 254,
  ki: 686,
  xk: 383,
  kw: 965,
  kg: 996,
  la: 856,
  lv: 371,
  lb: 961,
  ls: 266,
  lr: 231,
  ly: 218,
  li: 423,
  lt: 370,
  lu: 352,
  mo: 853,
  mk: 389,
  mg: 261,
  mw: 265,
  my: 60,
  mv: 960,
  ml: 223,
  mt: 356,
  mh: 692,
  mq: 596,
  mr: 222,
  mu: 230,
  yt: 262,
  mx: 52,
  fm: 691,
  md: 373,
  mc: 377,
  mn: 976,
  me: 382,
  ms: 1664,
  ma: 212,
  mz: 258,
  mm: 95,
  na: 264,
  nr: 674,
  np: 977,
  nl: 31,
  nc: 687,
  nz: 64,
  ni: 505,
  ne: 227,
  ng: 234,
  nu: 683,
  nf: 672,
  kp: 850,
  mp: 1670,
  no: 47,
  om: 968,
  pk: 92,
  pw: 680,
  ps: 970,
  pa: 507,
  pg: 675,
  py: 595,
  pe: 51,
  ph: 63,
  pn: 64,
  pl: 48,
  pt: 351,
  pr: 1,
  qa: 974,
  re: 262,
  ro: 40,
  ru: 7,
  rw: 250,
  bl: 590,
  sh: 290,
  kn: 1869,
  lc: 1758,
  mf: 590,
  pm: 508,
  vc: 1784,
  ws: 685,
  sm: 378,
  st: 239,
  sa: 966,
  sn: 221,
  rs: 381,
  sc: 248,
  sl: 232,
  sg: 65,
  sx: 1721,
  sk: 421,
  si: 386,
  sb: 677,
  so: 252,
  za: 27,
  gs: 500,
  kr: 82,
  ss: 211,
  es: 34,
  lk: 94,
  sd: 249,
  sr: 597,
  sj: 47,
  sz: 268,
  se: 46,
  ch: 41,
  sy: 963,
  tw: 886,
  tj: 992,
  tz: 255,
  th: 66,
  tl: 670,
  tg: 228,
  tk: 690,
  to: 676,
  tt: 1868,
  tn: 216,
  tr: 90,
  tm: 993,
  tc: 1649,
  tv: 688,
  vi: 1340,
  ug: 256,
  ua: 380,
  ae: 971,
  gb: 44,
  us: 1,
  um: 1,
  uy: 598,
  uz: 998,
  vu: 678,
  va: 39,
  ve: 58,
  vn: 84,
  wf: 681,
  eh: 212,
  ye: 967,
  zm: 260,
  zw: 263,
};

export const allCountries = [
  {
    name: "Afghanistan (‫افغانستان‬‎)",
    iso2: "af",
    dialCode: "93",
    priority: 0,
    format: "+..-..-...-....",
  },
  {
    name: "Åland Islands",
    iso2: "ax",
    dialCode: "358",
    priority: 0,
  },
  {
    name: "Albania (Shqipëri)",
    iso2: "al",
    dialCode: "355",
    priority: 0,
    format: "+...(...)...-...",
  },
  {
    name: "Algeria (‫الجزائر‬‎)",
    iso2: "dz",
    dialCode: "213",
    priority: 0,
    format: "+...-..-...-....",
  },
  {
    name: "American Samoa",
    iso2: "as",
    dialCode: "1684",
    priority: 0,
    format: "+.(...)...-....",
  },
  {
    name: "Andorra",
    iso2: "ad",
    dialCode: "376",
    priority: 0,
    format: "+...-...-...",
  },
  {
    name: "Angola",
    iso2: "ao",
    dialCode: "244",
    priority: 0,
    format: "+...(...)...-...",
  },
  {
    name: "Anguilla",
    iso2: "ai",
    dialCode: "1264",
    priority: 0,
    format: "+.(...)...-....",
  },
  {
    name: "Antarctica",
    iso2: "aq",
    dialCode: "672",
    priority: 0,
  },
  {
    name: "Antigua and Barbuda",
    iso2: "ag",
    dialCode: "1268",
    priority: 0,
    format: "+.(...)...-....",
  },
  {
    name: "Argentina",
    iso2: "ar",
    dialCode: "54",
    priority: 0,
    format: "+..(...)...-....",
  },
  {
    name: "Armenia (Հայաստան)",
    iso2: "am",
    dialCode: "374",
    priority: 0,
    format: "+...-..-...-...",
  },
  {
    name: "Aruba",
    iso2: "aw",
    dialCode: "297",
    priority: 0,
    format: "+...-...-....",
  },
  {
    name: "Australia",
    iso2: "au",
    dialCode: "61",
    priority: 0,
    format: "+.. ... ... ...",
  },
  {
    name: "Austria (Österreich)",
    iso2: "at",
    dialCode: "43",
    priority: 0,
    format: "+..(...)...-....",
  },
  {
    name: "Azerbaijan (Azərbaycan)",
    iso2: "az",
    dialCode: "994",
    priority: 0,
    format: "+...-..-...-..-..",
  },
  {
    name: "Bahamas",
    iso2: "bs",
    dialCode: "1242",
    priority: 0,
    format: "+.(...)...-....",
  },
  {
    name: "Bahrain (‫البحرين‬‎)",
    iso2: "bh",
    dialCode: "973",
    priority: 0,
    format: "+...-....-....",
  },
  {
    name: "Bangladesh (বাংলাদেশ)",
    iso2: "bd",
    dialCode: "880",
    priority: 0,
    format: "+...-..-...-...",
  },
  {
    name: "Barbados",
    iso2: "bb",
    dialCode: "1246",
    priority: 0,
    format: "+.(...)...-....",
  },
  {
    name: "Belarus (Беларусь)",
    iso2: "by",
    dialCode: "375",
    priority: 0,
    format: "+...(..)...-..-..",
  },
  {
    name: "Belgium (België)",
    iso2: "be",
    dialCode: "32",
    priority: 0,
    format: "+.. ... .. .. ..",
  },
  {
    name: "Belize",
    iso2: "bz",
    dialCode: "501",
    priority: 0,
    format: "+...-...-....",
  },
  {
    name: "Benin (Bénin)",
    iso2: "bj",
    dialCode: "229",
    priority: 0,
    format: "+...-..-..-....",
  },
  {
    name: "Bermuda",
    iso2: "bm",
    dialCode: "1441",
    priority: 0,
    format: "+.(...)...-....",
  },
  {
    name: "Bhutan (འབྲུག)",
    iso2: "bt",
    dialCode: "975",
    priority: 0,
    format: "+...-.-...-...",
  },
  {
    name: "Bolivia",
    iso2: "bo",
    dialCode: "591",
    priority: 0,
    format: "+...-.-...-....",
  },
  {
    name: "Bosnia and Herzegovina (Босна и Херцеговина)",
    iso2: "ba",
    dialCode: "387",
    priority: 0,
    format: "+...-..-....",
  },
  {
    name: "Botswana",
    iso2: "bw",
    dialCode: "267",
    priority: 0,
    format: "+...-..-...-...",
  },
  {
    name: "Bouvet Island",
    iso2: "bv",
    dialCode: "47",
    priority: 0,
  },
  {
    name: "Brazil (Brasil)",
    iso2: "br",
    dialCode: "55",
    priority: 0,
    format: "+..-..-....-....",
  },
  {
    name: "British Indian Ocean Territory",
    iso2: "io",
    dialCode: "246",
    priority: 0,
    format: "+...-...-....",
  },
  {
    name: "British Virgin Islands",
    iso2: "vg",
    dialCode: "1284",
    priority: 0,
    format: "+.(...)...-....",
  },
  {
    name: "Brunei",
    iso2: "bn",
    dialCode: "673",
    priority: 0,
    format: "+...-...-....",
  },
  {
    name: "Bulgaria (България)",
    iso2: "bg",
    dialCode: "359",
    priority: 0,
    format: "+...(...)...-...",
  },
  {
    name: "Burkina Faso",
    iso2: "bf",
    dialCode: "226",
    priority: 0,
    format: "+...-..-..-....",
  },
  {
    name: "Burundi (Uburundi)",
    iso2: "bi",
    dialCode: "257",
    priority: 0,
    format: "+...-..-..-....",
  },
  {
    name: "Cambodia (កម្ពុជា)",
    iso2: "kh",
    dialCode: "855",
    priority: 0,
    format: "+...-..-...-...",
  },
  {
    name: "Cameroon (Cameroun)",
    iso2: "cm",
    dialCode: "237",
    priority: 0,
    format: "+...-....-....",
  },
  {
    name: "Canada",
    iso2: "ca",
    dialCode: "1",
    priority: 1,
    format: "+. (...) ...-....",
    hasAreaCodes: true,
  },
  {
    name: "Cape Verde (Kabu Verdi)",
    iso2: "cv",
    dialCode: "238",
    priority: 0,
    format: "+...(...)..-..",
  },
  {
    name: "Caribbean Netherlands",
    iso2: "bq",
    dialCode: "599",
    priority: 1,
    format: "+...-...-....",
  },
  {
    name: "Cayman Islands",
    iso2: "ky",
    dialCode: "1345",
    priority: 0,
    format: "+.(...)...-....",
  },
  {
    name: "Central African Republic (République centrafricaine)",
    iso2: "cf",
    dialCode: "236",
    priority: 0,
    format: "+...-..-..-....",
  },
  {
    name: "Chad (Tchad)",
    iso2: "td",
    dialCode: "235",
    priority: 0,
    format: "+...-..-..-..-..",
  },
  {
    name: "Chile",
    iso2: "cl",
    dialCode: "56",
    priority: 0,
    format: "+..-.-....-....",
  },
  {
    name: "China (中国)",
    iso2: "cn",
    dialCode: "86",
    priority: 0,
    format: "+.. ..-........",
  },
  {
    name: "Christmas Island",
    iso2: "cx",
    dialCode: "61",
    priority: 0,
  },
  {
    name: "Cocos (Keeling) Islands",
    iso2: "cc",
    dialCode: "61",
    priority: 0,
  },
  {
    name: "Colombia",
    iso2: "co",
    dialCode: "57",
    priority: 0,
    format: "+..(...)...-....",
  },
  {
    name: "Comoros (‫جزر القمر‬‎)",
    iso2: "km",
    dialCode: "269",
    priority: 0,
    format: "+...-..-.....",
  },
  {
    name: "Congo (DRC) (Jamhuri ya Kidemokrasia ya Kongo)",
    iso2: "cd",
    dialCode: "243",
    priority: 0,
    format: "+...(...)...-...",
  },
  {
    name: "Congo (Republic) (Congo-Brazzaville)",
    iso2: "cg",
    dialCode: "242",
    priority: 0,
    format: "+...-..-...-....",
  },
  {
    name: "Cook Islands",
    iso2: "ck",
    dialCode: "682",
    priority: 0,
    format: "+...-..-...",
  },
  {
    name: "Costa Rica",
    iso2: "cr",
    dialCode: "506",
    priority: 0,
    format: "+... ....-....",
  },
  {
    name: "Côte d’Ivoire",
    iso2: "ci",
    dialCode: "225",
    priority: 0,
    format: "+...-..-...-...",
  },
  {
    name: "Croatia (Hrvatska)",
    iso2: "hr",
    dialCode: "385",
    priority: 0,
    format: "+...-..-...-...",
  },
  {
    name: "Cuba",
    iso2: "cu",
    dialCode: "53",
    priority: 0,
    format: "+..-.-...-....",
  },
  {
    name: "Curaçao",
    iso2: "cw",
    dialCode: "599",
    priority: 0,
    format: "+...-...-....",
  },
  {
    name: "Cyprus (Κύπρος)",
    iso2: "cy",
    dialCode: "357",
    priority: 0,
    format: "+...-..-...-...",
  },
  {
    name: "Czech Republic (Česká republika)",
    iso2: "cz",
    dialCode: "420",
    priority: 0,
    format: "+...(...)...-...",
  },
  {
    name: "Denmark (Danmark)",
    iso2: "dk",
    dialCode: "45",
    priority: 0,
    format: "+.. .. .. .. ..",
  },
  {
    name: "Djibouti",
    iso2: "dj",
    dialCode: "253",
    priority: 0,
    format: "+...-..-..-..-..",
  },
  {
    name: "Dominica",
    iso2: "dm",
    dialCode: "1767",
    priority: 0,
    format: "+.(...)...-....",
  },
  {
    name: "Dominican Republic (República Dominicana)",
    iso2: "do",
    dialCode: "1",
    priority: 2,
    format: "+.(...)...-....",
    hasAreaCodes: true,
  },
  {
    name: "Ecuador",
    iso2: "ec",
    dialCode: "593",
    priority: 0,
    format: "+...-.-...-....",
  },
  {
    name: "Egypt (‫مصر‬‎)",
    iso2: "eg",
    dialCode: "20",
    priority: 0,
    format: "+..(...)...-....",
  },
  {
    name: "El Salvador",
    iso2: "sv",
    dialCode: "503",
    priority: 0,
    format: "+... ....-....",
  },
  {
    name: "Equatorial Guinea (Guinea Ecuatorial)",
    iso2: "gq",
    dialCode: "240",
    priority: 0,
    format: "+...-..-...-....",
  },
  {
    name: "Eritrea",
    iso2: "er",
    dialCode: "291",
    priority: 0,
    format: "+...-.-...-...",
  },
  {
    name: "Estonia (Eesti)",
    iso2: "ee",
    dialCode: "372",
    priority: 0,
    format: "+...-...-....",
  },
  {
    name: "Ethiopia",
    iso2: "et",
    dialCode: "251",
    priority: 0,
    format: "+...-..-...-....",
  },
  {
    name: "Falkland Islands (Islas Malvinas)",
    iso2: "fk",
    dialCode: "500",
    priority: 0,
    format: "+...-.....",
  },
  {
    name: "Faroe Islands (Føroyar)",
    iso2: "fo",
    dialCode: "298",
    priority: 0,
    format: "+...-...-...",
  },
  {
    name: "Fiji",
    iso2: "fj",
    dialCode: "679",
    priority: 0,
    format: "+...-..-.....",
  },
  {
    name: "Finland (Suomi)",
    iso2: "fi",
    dialCode: "358",
    priority: 0,
    format: "+... .. .... ....",
  },
  {
    name: "France",
    iso2: "fr",
    dialCode: "33",
    priority: 0,
    format: "+.. . .. .. .. ..",
  },
  {
    name: "French Guiana (Guyane française)",
    iso2: "gf",
    dialCode: "594",
    priority: 0,
    format: "+...-.....-....",
  },
  {
    name: "French Polynesia (Polynésie française)",
    iso2: "pf",
    dialCode: "689",
    priority: 0,
    format: "+...-..-..-..",
  },
  {
    name: "French Southern and Antarctic Lands",
    iso2: "tf",
    dialCode: "262",
    priority: 0,
  },
  {
    name: "Gabon",
    iso2: "ga",
    dialCode: "241",
    priority: 0,
    format: "+...-.-..-..-..",
  },
  {
    name: "Gambia",
    iso2: "gm",
    dialCode: "220",
    priority: 0,
    format: "+...(...)..-..",
  },
  {
    name: "Georgia (საქართველო)",
    iso2: "ge",
    dialCode: "995",
    priority: 0,
    format: "+...(...)...-...",
  },
  {
    name: "Germany (Deutschland)",
    iso2: "de",
    dialCode: "49",
    priority: 0,
    format: "+.. ... .......",
  },
  {
    name: "Ghana (Gaana)",
    iso2: "gh",
    dialCode: "233",
    priority: 0,
    format: "+...(...)...-...",
  },
  {
    name: "Gibraltar",
    iso2: "gi",
    dialCode: "350",
    priority: 0,
    format: "+...-...-.....",
  },
  {
    name: "Greece (Ελλάδα)",
    iso2: "gr",
    dialCode: "30",
    priority: 0,
    format: "+..(...)...-....",
  },
  {
    name: "Greenland (Kalaallit Nunaat)",
    iso2: "gl",
    dialCode: "299",
    priority: 0,
    format: "+...-..-..-..",
  },
  {
    name: "Grenada",
    iso2: "gd",
    dialCode: "1473",
    priority: 0,
    format: "+.(...)...-....",
  },
  {
    name: "Guadeloupe",
    iso2: "gp",
    dialCode: "590",
    priority: 0,
  },
  {
    name: "Guam",
    iso2: "gu",
    dialCode: "1671",
    priority: 0,
    format: "+.(...)...-....",
  },
  {
    name: "Guatemala",
    iso2: "gt",
    dialCode: "502",
    priority: 0,
    format: "+... ....-....",
  },
  {
    name: "Guernsey",
    iso2: "gg",
    dialCode: "44",
    priority: 0,
  },
  {
    name: "Guinea (Guinée)",
    iso2: "gn",
    dialCode: "224",
    priority: 0,
    format: "+...-..-...-...",
  },
  {
    name: "Guinea-Bissau (Guiné Bissau)",
    iso2: "gw",
    dialCode: "245",
    priority: 0,
    format: "+...-.-......",
  },
  {
    name: "Guyana",
    iso2: "gy",
    dialCode: "592",
    priority: 0,
    format: "+...-...-....",
  },
  {
    name: "Haiti",
    iso2: "ht",
    dialCode: "509",
    priority: 0,
    format: "+... ....-....",
  },
  {
    name: "Heard Island and McDonald Islands",
    iso2: "hm",
    dialCode: "672",
    priority: 0,
  },
  {
    name: "Honduras",
    iso2: "hn",
    dialCode: "504",
    priority: 0,
    format: "+...-....-....",
  },
  {
    name: "Hong Kong (香港)",
    iso2: "hk",
    dialCode: "852",
    priority: 0,
    format: "+... .... ....",
  },
  {
    name: "Hungary (Magyarország)",
    iso2: "hu",
    dialCode: "36",
    priority: 0,
    format: "+..(...)...-...",
  },
  {
    name: "Iceland (Ísland)",
    iso2: "is",
    dialCode: "354",
    priority: 0,
    format: "+... ... ....",
  },
  {
    name: "India (भारत)",
    iso2: "in",
    dialCode: "91",
    priority: 0,
    format: "+.. .....-.....",
  },
  {
    name: "Indonesia",
    iso2: "id",
    dialCode: "62",
    priority: 0,
    format: "+..-..-...-..",
  },
  {
    name: "Iran (‫ایران‬‎)",
    iso2: "ir",
    dialCode: "98",
    priority: 0,
    format: "+..(...)...-....",
  },
  {
    name: "Iraq (‫العراق‬‎)",
    iso2: "iq",
    dialCode: "964",
    priority: 0,
    format: "+...(...)...-....",
  },
  {
    name: "Ireland",
    iso2: "ie",
    dialCode: "353",
    priority: 0,
    format: "+... .. .......",
  },
  {
    name: "Isle of Man",
    iso2: "im",
    dialCode: "44",
    priority: 0,
  },
  {
    name: "Israel (‫ישראל‬‎)",
    iso2: "il",
    dialCode: "972",
    priority: 0,
    format: "+...-.-...-....",
  },
  {
    name: "Italy (Italia)",
    iso2: "it",
    dialCode: "39",
    priority: 0,
    format: "+.. ... ......",
  },
  {
    name: "Jamaica",
    iso2: "jm",
    dialCode: "1876",
    priority: 0,
    format: "+.(...)...-....",
  },
  {
    name: "Japan (日本)",
    iso2: "jp",
    dialCode: "81",
    priority: 0,
    format: "+.. ... .. ....",
  },
  {
    name: "Jersey",
    iso2: "je",
    dialCode: "44",
    priority: 0,
  },
  {
    name: "Jordan (‫الأردن‬‎)",
    iso2: "jo",
    dialCode: "962",
    priority: 0,
    format: "+...-.-....-....",
  },
  {
    name: "Kazakhstan (Казахстан)",
    iso2: "kz",
    dialCode: "7",
    priority: 1,
    format: "+. ... ...-..-..",
  },
  {
    name: "Kenya",
    iso2: "ke",
    dialCode: "254",
    priority: 0,
    format: "+...-...-......",
  },
  {
    name: "Kiribati",
    iso2: "ki",
    dialCode: "686",
    priority: 0,
    format: "+...-..-...",
  },
  {
    name: "Kosovo",
    iso2: "xk",
    dialCode: "383",
    priority: 0,
  },
  {
    name: "Kuwait (‫الكويت‬‎)",
    iso2: "kw",
    dialCode: "965",
    priority: 0,
    format: "+...-....-....",
  },
  {
    name: "Kyrgyzstan (Кыргызстан)",
    iso2: "kg",
    dialCode: "996",
    priority: 0,
    format: "+...(...)...-...",
  },
  {
    name: "Laos (ລາວ)",
    iso2: "la",
    dialCode: "856",
    priority: 0,
    format: "+...-..-...-...",
  },
  {
    name: "Latvia (Latvija)",
    iso2: "lv",
    dialCode: "371",
    priority: 0,
    format: "+...-..-...-...",
  },
  {
    name: "Lebanon (‫لبنان‬‎)",
    iso2: "lb",
    dialCode: "961",
    priority: 0,
    format: "+...-.-...-...",
  },
  {
    name: "Lesotho",
    iso2: "ls",
    dialCode: "266",
    priority: 0,
    format: "+...-.-...-....",
  },
  {
    name: "Liberia",
    iso2: "lr",
    dialCode: "231",
    priority: 0,
    format: "+...-..-...-...",
  },
  {
    name: "Libya (‫ليبيا‬‎)",
    iso2: "ly",
    dialCode: "218",
    priority: 0,
    format: "+...-..-...-...",
  },
  {
    name: "Liechtenstein",
    iso2: "li",
    dialCode: "423",
    priority: 0,
    format: "+...(...)...-....",
  },
  {
    name: "Lithuania (Lietuva)",
    iso2: "lt",
    dialCode: "370",
    priority: 0,
    format: "+...(...)..-...",
  },
  {
    name: "Luxembourg",
    iso2: "lu",
    dialCode: "352",
    priority: 0,
    format: "+...(...)...-...",
  },
  {
    name: "Macau (澳門)",
    iso2: "mo",
    dialCode: "853",
    priority: 0,
    format: "+...-....-....",
  },
  {
    name: "Macedonia (FYROM) (Македонија)",
    iso2: "mk",
    dialCode: "389",
    priority: 0,
    format: "+...-..-...-...",
  },
  {
    name: "Madagascar (Madagasikara)",
    iso2: "mg",
    dialCode: "261",
    priority: 0,
    format: "+...-..-..-.....",
  },
  {
    name: "Malawi",
    iso2: "mw",
    dialCode: "265",
    priority: 0,
    format: "+...-.-....-....",
  },
  {
    name: "Malaysia",
    iso2: "my",
    dialCode: "60",
    priority: 0,
    format: "+.. ..-....-....",
  },
  {
    name: "Maldives",
    iso2: "mv",
    dialCode: "960",
    priority: 0,
    format: "+...-...-....",
  },
  {
    name: "Mali",
    iso2: "ml",
    dialCode: "223",
    priority: 0,
    format: "+...-..-..-....",
  },
  {
    name: "Malta",
    iso2: "mt",
    dialCode: "356",
    priority: 0,
    format: "+...-....-....",
  },
  {
    name: "Marshall Islands",
    iso2: "mh",
    dialCode: "692",
    priority: 0,
    format: "+...-...-....",
  },
  {
    name: "Martinique",
    iso2: "mq",
    dialCode: "596",
    priority: 0,
    format: "+...(...)..-..-..",
  },
  {
    name: "Mauritania (‫موريتانيا‬‎)",
    iso2: "mr",
    dialCode: "222",
    priority: 0,
    format: "+...-..-..-....",
  },
  {
    name: "Mauritius (Moris)",
    iso2: "mu",
    dialCode: "230",
    priority: 0,
    format: "+...-...-....",
  },
  {
    name: "Mayotte",
    iso2: "yt",
    dialCode: "262",
    priority: 0,
  },
  {
    name: "Mexico (México)",
    iso2: "mx",
    dialCode: "52",
    priority: 0,
    format: "+..-..-..-....",
  },
  {
    name: "Micronesia",
    iso2: "fm",
    dialCode: "691",
    priority: 0,
    format: "+...-...-....",
  },
  {
    name: "Moldova (Republica Moldova)",
    iso2: "md",
    dialCode: "373",
    priority: 0,
    format: "+...-....-....",
  },
  {
    name: "Monaco",
    iso2: "mc",
    dialCode: "377",
    priority: 0,
    format: "+...-..-...-...",
  },
  {
    name: "Mongolia (Монгол)",
    iso2: "mn",
    dialCode: "976",
    priority: 0,
    format: "+...-..-..-....",
  },
  {
    name: "Montenegro (Crna Gora)",
    iso2: "me",
    dialCode: "382",
    priority: 0,
    format: "+...-..-...-...",
  },
  {
    name: "Montserrat",
    iso2: "ms",
    dialCode: "1664",
    priority: 0,
    format: "+.(...)...-....",
  },
  {
    name: "Morocco (‫المغرب‬‎)",
    iso2: "ma",
    dialCode: "212",
    priority: 0,
    format: "+...-..-....-...",
  },
  {
    name: "Mozambique (Moçambique)",
    iso2: "mz",
    dialCode: "258",
    priority: 0,
    format: "+...-..-...-...",
  },
  {
    name: "Myanmar (Burma) (မြန်မာ)",
    iso2: "mm",
    dialCode: "95",
    priority: 0,
    format: "+..-...-...",
  },
  {
    name: "Namibia (Namibië)",
    iso2: "na",
    dialCode: "264",
    priority: 0,
    format: "+...-..-...-....",
  },
  {
    name: "Nauru",
    iso2: "nr",
    dialCode: "674",
    priority: 0,
    format: "+...-...-....",
  },
  {
    name: "Nepal (नेपाल)",
    iso2: "np",
    dialCode: "977",
    priority: 0,
    format: "+...-..-...-...",
  },
  {
    name: "Netherlands (Nederland)",
    iso2: "nl",
    dialCode: "31",
    priority: 0,
    format: "+.. .. ........",
  },
  {
    name: "New Caledonia (Nouvelle-Calédonie)",
    iso2: "nc",
    dialCode: "687",
    priority: 0,
    format: "+...-..-....",
  },
  {
    name: "New Zealand",
    iso2: "nz",
    dialCode: "64",
    priority: 0,
    format: "+.. ...-...-....",
  },
  {
    name: "Nicaragua",
    iso2: "ni",
    dialCode: "505",
    priority: 0,
    format: "+...-....-....",
  },
  {
    name: "Niger (Nijar)",
    iso2: "ne",
    dialCode: "227",
    priority: 0,
    format: "+...-..-..-....",
  },
  {
    name: "Nigeria",
    iso2: "ng",
    dialCode: "234",
    priority: 0,
    format: "+...-..-...-..",
  },
  {
    name: "Niue",
    iso2: "nu",
    dialCode: "683",
    priority: 0,
    format: "+...-....",
  },
  {
    name: "Norfolk Island",
    iso2: "nf",
    dialCode: "672",
    priority: 0,
    format: "+...-...-...",
  },
  {
    name: "North Korea (조선 민주주의 인민 공화국)",
    iso2: "kp",
    dialCode: "850",
    priority: 0,
    format: "+...-...-...",
  },
  {
    name: "Northern Mariana Islands",
    iso2: "mp",
    dialCode: "1670",
    priority: 0,
    format: "+.(...)...-....",
  },
  {
    name: "Norway (Norge)",
    iso2: "no",
    dialCode: "47",
    priority: 0,
    format: "+.. ... .. ...",
  },
  {
    name: "Oman (‫عُمان‬‎)",
    iso2: "om",
    dialCode: "968",
    priority: 0,
    format: "+...-..-...-...",
  },
  {
    name: "Pakistan (‫پاکستان‬‎)",
    iso2: "pk",
    dialCode: "92",
    priority: 0,
    format: "+.. ...-.......",
  },
  {
    name: "Palau",
    iso2: "pw",
    dialCode: "680",
    priority: 0,
    format: "+...-...-....",
  },
  {
    name: "Palestine (‫فلسطين‬‎)",
    iso2: "ps",
    dialCode: "970",
    priority: 0,
    format: "+...-..-...-....",
  },
  {
    name: "Panama (Panamá)",
    iso2: "pa",
    dialCode: "507",
    priority: 0,
    format: "+...-...-....",
  },
  {
    name: "Papua New Guinea",
    iso2: "pg",
    dialCode: "675",
    priority: 0,
    format: "+...(...)..-...",
  },
  {
    name: "Paraguay",
    iso2: "py",
    dialCode: "595",
    priority: 0,
    format: "+...(...)...-...",
  },
  {
    name: "Peru (Perú)",
    iso2: "pe",
    dialCode: "51",
    priority: 0,
    format: "+..(...)...-...",
  },
  {
    name: "Philippines",
    iso2: "ph",
    dialCode: "63",
    priority: 0,
    format: "+.. ... ....",
  },
  {
    name: "Pitcairn Islands",
    iso2: "pn",
    dialCode: "64",
    priority: 0,
  },
  {
    name: "Poland (Polska)",
    iso2: "pl",
    dialCode: "48",
    priority: 0,
    format: "+.. ...-...-...",
  },
  {
    name: "Portugal",
    iso2: "pt",
    dialCode: "351",
    priority: 0,
    format: "+...-..-...-....",
  },
  {
    name: "Puerto Rico",
    iso2: "pr",
    dialCode: "1",
    priority: 3,
    format: "+. (...) ...-....",
    hasAreaCodes: true,
  },
  {
    name: "Qatar (‫قطر‬‎)",
    iso2: "qa",
    dialCode: "974",
    priority: 0,
    format: "+...-....-....",
  },
  {
    name: "Réunion (La Réunion)",
    iso2: "re",
    dialCode: "262",
    priority: 0,
    format: "+...-.....-....",
  },
  {
    name: "Romania (România)",
    iso2: "ro",
    dialCode: "40",
    priority: 0,
    format: "+..-..-...-....",
  },
  {
    name: "Russia (Россия)",
    iso2: "ru",
    dialCode: "7",
    priority: 0,
    format: "+. ... ...-..-..",
  },
  {
    name: "Rwanda",
    iso2: "rw",
    dialCode: "250",
    priority: 0,
    format: "+...(...)...-...",
  },
  {
    name: "Saint Barthélemy (Saint-Barthélemy)",
    iso2: "bl",
    dialCode: "590",
    priority: 1,
  },
  {
    name: "Saint Helena",
    iso2: "sh",
    dialCode: "290",
    priority: 0,
  },
  {
    name: "Saint Kitts and Nevis",
    iso2: "kn",
    dialCode: "1869",
    priority: 0,
    format: "+.(...)...-....",
  },
  {
    name: "Saint Lucia",
    iso2: "lc",
    dialCode: "1758",
    priority: 0,
    format: "+.(...)...-....",
  },
  {
    name: "Saint Martin (Saint-Martin (partie française))",
    iso2: "mf",
    dialCode: "590",
    priority: 2,
  },
  {
    name: "Saint Pierre and Miquelon (Saint-Pierre-et-Miquelon)",
    iso2: "pm",
    dialCode: "508",
    priority: 0,
  },
  {
    name: "Saint Vincent and the Grenadines",
    iso2: "vc",
    dialCode: "1784",
    priority: 0,
    format: "+.(...)...-....",
  },
  {
    name: "Samoa",
    iso2: "ws",
    dialCode: "685",
    priority: 0,
    format: "+...-..-....",
  },
  {
    name: "San Marino",
    iso2: "sm",
    dialCode: "378",
    priority: 0,
    format: "+...-....-......",
  },
  {
    name: "São Tomé and Príncipe (São Tomé e Príncipe)",
    iso2: "st",
    dialCode: "239",
    priority: 0,
    format: "+...-..-.....",
  },
  {
    name: "Saudi Arabia (‫المملكة العربية السعودية‬‎)",
    iso2: "sa",
    dialCode: "966",
    priority: 0,
    format: "+...-.-...-....",
  },
  {
    name: "Senegal (Sénégal)",
    iso2: "sn",
    dialCode: "221",
    priority: 0,
    format: "+...-..-...-....",
  },
  {
    name: "Serbia (Србија)",
    iso2: "rs",
    dialCode: "381",
    priority: 0,
    format: "+...-..-...-....",
  },
  {
    name: "Seychelles",
    iso2: "sc",
    dialCode: "248",
    priority: 0,
    format: "+...-.-...-...",
  },
  {
    name: "Sierra Leone",
    iso2: "sl",
    dialCode: "232",
    priority: 0,
    format: "+...-..-......",
  },
  {
    name: "Singapore",
    iso2: "sg",
    dialCode: "65",
    priority: 0,
    format: "+.. ....-....",
  },
  {
    name: "Sint Maarten",
    iso2: "sx",
    dialCode: "1721",
    priority: 0,
    format: "+.(...)...-....",
  },
  {
    name: "Slovakia (Slovensko)",
    iso2: "sk",
    dialCode: "421",
    priority: 0,
    format: "+...(...)...-...",
  },
  {
    name: "Slovenia (Slovenija)",
    iso2: "si",
    dialCode: "386",
    priority: 0,
    format: "+...-..-...-...",
  },
  {
    name: "Solomon Islands",
    iso2: "sb",
    dialCode: "677",
    priority: 0,
    format: "+...-.....",
  },
  {
    name: "Somalia (Soomaaliya)",
    iso2: "so",
    dialCode: "252",
    priority: 0,
    format: "+...-.-...-...",
  },
  {
    name: "South Africa",
    iso2: "za",
    dialCode: "27",
    priority: 0,
    format: "+..-..-...-....",
  },
  {
    name: "South Georgia and the South Sandwich Islands",
    iso2: "gs",
    dialCode: "500",
    priority: 0,
  },
  {
    name: "South Korea (대한민국)",
    iso2: "kr",
    dialCode: "82",
    priority: 0,
    format: "+..-..-...-....",
  },
  {
    name: "South Sudan (‫جنوب السودان‬‎)",
    iso2: "ss",
    dialCode: "211",
    priority: 0,
    format: "+...-..-...-....",
  },
  {
    name: "Spain (España)",
    iso2: "es",
    dialCode: "34",
    priority: 0,
    format: "+.. ... ... ...",
  },
  {
    name: "Sri Lanka (ශ්‍රී ලංකාව)",
    iso2: "lk",
    dialCode: "94",
    priority: 0,
    format: "+..-..-...-....",
  },
  {
    name: "Sudan (‫السودان‬‎)",
    iso2: "sd",
    dialCode: "249",
    priority: 0,
    format: "+...-..-...-....",
  },
  {
    name: "Suriname",
    iso2: "sr",
    dialCode: "597",
    priority: 0,
    format: "+...-...-...",
  },
  {
    name: "Svalbard and Jan Mayen",
    iso2: "sj",
    dialCode: "47",
    priority: 0,
  },
  {
    name: "Swaziland",
    iso2: "sz",
    dialCode: "268",
    priority: 0,
    format: "+...-..-..-....",
  },
  {
    name: "Sweden (Sverige)",
    iso2: "se",
    dialCode: "46",
    priority: 0,
    format: "+.. .. ... .. ..",
  },
  {
    name: "Switzerland (Schweiz)",
    iso2: "ch",
    dialCode: "41",
    priority: 0,
    format: "+.. .. ... .. ..",
  },
  {
    name: "Syria (‫سوريا‬‎)",
    iso2: "sy",
    dialCode: "963",
    priority: 0,
    format: "+...-..-....-...",
  },
  {
    name: "Taiwan (台灣)",
    iso2: "tw",
    dialCode: "886",
    priority: 0,
    format: "+...-....-....",
  },
  {
    name: "Tajikistan",
    iso2: "tj",
    dialCode: "992",
    priority: 0,
    format: "+...-..-...-....",
  },
  {
    name: "Tanzania",
    iso2: "tz",
    dialCode: "255",
    priority: 0,
    format: "+...-..-...-....",
  },
  {
    name: "Thailand (ไทย)",
    iso2: "th",
    dialCode: "66",
    priority: 0,
    format: "+..-..-...-...",
  },
  {
    name: "Timor-Leste",
    iso2: "tl",
    dialCode: "670",
    priority: 0,
    format: "+...-...-....",
  },
  {
    name: "Togo",
    iso2: "tg",
    dialCode: "228",
    priority: 0,
    format: "+...-..-...-...",
  },
  {
    name: "Tokelau",
    iso2: "tk",
    dialCode: "690",
    priority: 0,
    format: "+...-....",
  },
  {
    name: "Tonga",
    iso2: "to",
    dialCode: "676",
    priority: 0,
    format: "+...-.....",
  },
  {
    name: "Trinidad and Tobago",
    iso2: "tt",
    dialCode: "1868",
    priority: 0,
    format: "+.(...)...-....",
  },
  {
    name: "Tunisia (‫تونس‬‎)",
    iso2: "tn",
    dialCode: "216",
    priority: 0,
    format: "+...-..-...-...",
  },
  {
    name: "Turkey (Türkiye)",
    iso2: "tr",
    dialCode: "90",
    priority: 0,
    format: "+.. ... ... .. ..",
  },
  {
    name: "Turkmenistan",
    iso2: "tm",
    dialCode: "993",
    priority: 0,
    format: "+...-.-...-....",
  },
  {
    name: "Turks and Caicos Islands",
    iso2: "tc",
    dialCode: "1649",
    priority: 0,
    format: "+.(...)...-....",
  },
  {
    name: "Tuvalu",
    iso2: "tv",
    dialCode: "688",
    priority: 0,
    format: "+...-.....",
  },
  {
    name: "U.S. Virgin Islands",
    iso2: "vi",
    dialCode: "1340",
    priority: 0,
    format: "+.(...)...-....",
  },
  {
    name: "Uganda",
    iso2: "ug",
    dialCode: "256",
    priority: 0,
    format: "+...(...)...-...",
  },
  {
    name: "Ukraine (Україна)",
    iso2: "ua",
    dialCode: "380",
    priority: 0,
    format: "+...(..)...-..-..",
  },
  {
    name: "United Arab Emirates (‫الإمارات العربية المتحدة‬‎)",
    iso2: "ae",
    dialCode: "971",
    priority: 0,
    format: "+...-.-...-....",
  },
  {
    name: "United Kingdom",
    iso2: "gb",
    dialCode: "44",
    priority: 0,
    format: "+.. .... ......",
  },
  {
    name: "United States",
    iso2: "us",
    dialCode: "1",
    priority: 0,
    format: "+. (...) ...-....",
  },
  {
    name: "United States Minor Outlying Islands",
    iso2: "um",
    dialCode: "1",
    priority: 0,
  },
  {
    name: "Uruguay",
    iso2: "uy",
    dialCode: "598",
    priority: 0,
    format: "+...-.-...-..-..",
  },
  {
    name: "Uzbekistan (Oʻzbekiston)",
    iso2: "uz",
    dialCode: "998",
    priority: 0,
    format: "+...-..-...-....",
  },
  {
    name: "Vanuatu",
    iso2: "vu",
    dialCode: "678",
    priority: 0,
    format: "+...-.....",
  },
  {
    name: "Vatican City (Città del Vaticano)",
    iso2: "va",
    dialCode: "39",
    priority: 1,
    format: "+.. .. .... ....",
  },
  {
    name: "Venezuela",
    iso2: "ve",
    dialCode: "58",
    priority: 0,
    format: "+..(...)...-....",
  },
  {
    name: "Vietnam (Việt Nam)",
    iso2: "vn",
    dialCode: "84",
    priority: 0,
    format: "+..-..-....-...",
  },
  {
    name: "Wallis and Futuna",
    iso2: "wf",
    dialCode: "681",
    priority: 0,
    format: "+...-..-....",
  },
  {
    name: "Western Sahara",
    iso2: "eh",
    dialCode: "212",
    priority: 0,
    format: "+...-..-....",
  },
  {
    name: "Yemen (‫اليمن‬‎)",
    iso2: "ye",
    dialCode: "967",
    priority: 0,
    format: "+...-.-...-...",
  },
  {
    name: "Zambia",
    iso2: "zm",
    dialCode: "260",
    priority: 0,
    format: "+...-..-...-....",
  },
  {
    name: "Zimbabwe",
    iso2: "zw",
    dialCode: "263",
    priority: 0,
    format: "+...-.-......",
  },
];
